import type { Tenant } from "../types";

export const semillaFranca: Tenant = {
  slug: "semilla-franca",
  name: "Semilla Franca",
  tagline: "Grow shop · genéticas de banco",
  niche: "Insumos de cultivo",
  whatsapp: "5491100000000",
  instagram: "https://instagram.com/semillafranca",
  currency: "ARS",
  locale: "es-AR",
  theme: {
    bg: "#efeee1",
    bgAlt: "#e6e4d1",
    surface: "#fbfaf3",
    surfaceAlt: "#f2f0e4",
    text: "#1c1d13",
    textMuted: "#63624f",
    border: "#d8d5bd",
    accent: "#a9711b",
    accentStrong: "#8a5a13",
    accentInk: "#fbf3e2",
    success: "#3f6b3e",
    successInk: "#eef4ec",
    radius: "14px",
    fontPreset: "editorial-warm",
  },
  hero: {
    eyebrow: "BSF · Seedstockers · Sweet Seeds · Kannabia · Fast Buds",
    heading: "Genética de banco, trato de vivero de barrio.",
    description:
      "Traemos genéticas de los bancos que ya conocés, con stock real y ficha de cada variedad. Elegís por WhatsApp, coordinamos envío o retiro.",
  },
  contactNote:
    "Envíos a todo el país por correo privado y retiro en Paraná. El pago se coordina por WhatsApp al confirmar el pedido.",
  legalNote:
    "Semillas de cannabis para colección de genéticas y autocultivo responsable en el marco de la Ley 27.350. Venta exclusiva a mayores de 18 años.",
  filterGroups: [
    {
      id: "tipo",
      label: "Tipo",
      options: [
        { id: "auto", label: "Autoflorecientes" },
        { id: "foto", label: "Fotoperiódicas" },
        { id: "regular", label: "Regulares" },
      ],
    },
    {
      id: "banco",
      label: "Banco",
      options: [
        { id: "bsf", label: "BSF Seeds" },
        { id: "seedstockers", label: "Seedstockers" },
        { id: "sweetseeds", label: "Sweet Seeds" },
        { id: "kannabia", label: "Kannabia" },
        { id: "fastbuds", label: "Fast Buds" },
      ],
    },
  ],
  products: [
    {
      id: "pampa-haze",
      name: "Pampa Haze",
      subtitle: "Fast Buds · 60% Sativa / 40% Índica",
      categoryIds: ["foto", "fastbuds"],
      price: 14000,
      priceNote: "por pack x5",
      stock: "Quedan 6",
      specs: [
        { label: "Floración", value: "9-10 sem" },
        { label: "THC", value: "19-22%" },
        { label: "Pack", value: "x5 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Fotoperiódica", "Feminizada"],
      artSeed: "pampa-haze",
      featured: true,
    },
    {
      id: "delta-kush",
      name: "Delta Kush",
      subtitle: "BSF Seeds · 70% Índica / 30% Sativa",
      categoryIds: ["foto", "bsf"],
      price: 9800,
      priceNote: "por pack x3",
      stock: "Quedan 11",
      specs: [
        { label: "Floración", value: "8-9 sem" },
        { label: "THC", value: "20-24%" },
        { label: "Pack", value: "x3 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Fotoperiódica", "Feminizada"],
      artSeed: "delta-kush",
    },
    {
      id: "iguazu-autoflor",
      name: "Iguazú Autoflor",
      subtitle: "Seedstockers · Índica dominante",
      categoryIds: ["auto", "seedstockers"],
      price: 12500,
      priceNote: "por pack x5",
      stock: "Quedan 14",
      specs: [
        { label: "Floración", value: "9-10 sem" },
        { label: "THC", value: "16-19%" },
        { label: "Pack", value: "x5 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Autofloreciente", "Feminizada"],
      artSeed: "iguazu-autoflor",
      featured: true,
    },
    {
      id: "patagonia-og",
      name: "Patagonia OG",
      subtitle: "Kannabia · 80% Índica / 20% Sativa",
      categoryIds: ["foto", "kannabia"],
      price: 11200,
      priceNote: "por pack x3",
      stock: "Quedan 4",
      specs: [
        { label: "Floración", value: "7-8 sem" },
        { label: "THC", value: "21-25%" },
        { label: "Pack", value: "x3 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Fotoperiódica", "Feminizada"],
      artSeed: "patagonia-og",
    },
    {
      id: "litoral-amnesia",
      name: "Litoral Amnesia",
      subtitle: "Sweet Seeds · 65% Sativa / 35% Índica",
      categoryIds: ["foto", "sweetseeds"],
      price: 15800,
      priceNote: "por pack x10",
      stock: "Quedan 9",
      specs: [
        { label: "Floración", value: "10-11 sem" },
        { label: "THC", value: "17-20%" },
        { label: "Pack", value: "x10 semillas" },
        { label: "Tipo", value: "Regular" },
      ],
      badges: ["Fotoperiódica", "Regular"],
      artSeed: "litoral-amnesia",
    },
    {
      id: "criolla-fuerte",
      name: "Criolla Fuerte",
      subtitle: "BSF Seeds · Híbrida equilibrada",
      categoryIds: ["regular", "bsf"],
      price: 10400,
      priceNote: "por pack x10",
      stock: "Quedan 20",
      specs: [
        { label: "Floración", value: "9 sem" },
        { label: "THC", value: "14-17%" },
        { label: "Pack", value: "x10 semillas" },
        { label: "Tipo", value: "Regular" },
      ],
      badges: ["Fotoperiódica", "Regular"],
      artSeed: "criolla-fuerte",
    },
    {
      id: "malbec-kush",
      name: "Malbec Kush",
      subtitle: "Fast Buds · 75% Índica / 25% Sativa",
      categoryIds: ["foto", "fastbuds"],
      price: 13600,
      priceNote: "por pack x3",
      stock: "Quedan 3",
      specs: [
        { label: "Floración", value: "8 sem" },
        { label: "THC", value: "22-26%" },
        { label: "Pack", value: "x3 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Fotoperiódica", "Feminizada"],
      artSeed: "malbec-kush",
    },
    {
      id: "correntina-auto",
      name: "Correntina Auto",
      subtitle: "Kannabia · Híbrida equilibrada",
      categoryIds: ["auto", "kannabia"],
      price: 11900,
      priceNote: "por pack x5",
      stock: "Quedan 17",
      specs: [
        { label: "Floración", value: "8-9 sem" },
        { label: "THC", value: "15-18%" },
        { label: "Pack", value: "x5 semillas" },
        { label: "Tipo", value: "Feminizada" },
      ],
      badges: ["Autofloreciente", "Feminizada"],
      artSeed: "correntina-auto",
    },
  ],
};
