import type { Tenant } from "../types";

export const veraStudio: Tenant = {
  slug: "vera-studio",
  name: "Vera Studio",
  tagline: "Indumentaria · ediciones limitadas",
  niche: "Indumentaria",
  whatsapp: "5491100000001",
  instagram: "https://instagram.com/vera.studio",
  currency: "ARS",
  locale: "es-AR",
  theme: {
    bg: "#f6f5f1",
    bgAlt: "#ebe9e2",
    surface: "#ffffff",
    surfaceAlt: "#f0efe9",
    text: "#141414",
    textMuted: "#66625a",
    border: "#dedad0",
    accent: "#c81d25",
    accentStrong: "#a3161d",
    accentInk: "#fdf1ec",
    success: "#1c1d13",
    successInk: "#f6f5f1",
    radius: "2px",
    fontPreset: "editorial-bold",
  },
  hero: {
    eyebrow: "Tiradas cortas · Buenos Aires",
    heading: "Prendas de tanda chica, hechas para durar.",
    description:
      "Cada tanda sale en cantidades limitadas. Elegís talle y color por WhatsApp y coordinamos envío o retiro por el showroom.",
  },
  contactNote:
    "Envíos con Correo Argentino a todo el país y retiro en Palermo con turno previo. El pago se confirma por WhatsApp al separar la prenda.",
  filterGroups: [
    {
      id: "categoria",
      label: "Categoría",
      options: [
        { id: "abrigo", label: "Abrigo" },
        { id: "remeras", label: "Remeras" },
        { id: "pantalones", label: "Pantalones" },
        { id: "accesorios", label: "Accesorios" },
      ],
    },
    {
      id: "talle",
      label: "Talle",
      options: [
        { id: "s", label: "S" },
        { id: "m", label: "M" },
        { id: "l", label: "L" },
        { id: "xl", label: "XL" },
      ],
    },
  ],
  products: [
    {
      id: "campera-tanda-04",
      name: "Campera Tanda 04",
      subtitle: "Gabardina cruda · forro completo",
      categoryIds: ["abrigo", "m"],
      price: 78000,
      stock: "Quedan 5",
      specs: [
        { label: "Tela", value: "Gabardina 100% algodón" },
        { label: "Calce", value: "Oversize" },
        { label: "Talles", value: "S – XL" },
      ],
      badges: ["Tanda 04", "Edición limitada"],
      artSeed: "campera-tanda-04",
      featured: true,
    },
    {
      id: "remera-oficio",
      name: "Remera Oficio",
      subtitle: "Jersey pesado 220g",
      categoryIds: ["remeras", "l"],
      price: 24000,
      stock: "Stock alto",
      specs: [
        { label: "Tela", value: "Jersey 220g" },
        { label: "Calce", value: "Regular" },
        { label: "Talles", value: "S – XL" },
      ],
      badges: ["Básico"],
      artSeed: "remera-oficio",
    },
    {
      id: "pantalon-recto-crudo",
      name: "Pantalón Recto Crudo",
      subtitle: "Sarga rígida · tiro alto",
      categoryIds: ["pantalones", "m"],
      price: 52000,
      stock: "Quedan 8",
      specs: [
        { label: "Tela", value: "Sarga de algodón" },
        { label: "Calce", value: "Recto, tiro alto" },
        { label: "Talles", value: "S – L" },
      ],
      badges: ["Tanda 04"],
      artSeed: "pantalon-recto-crudo",
      featured: true,
    },
    {
      id: "remera-doble-tela",
      name: "Remera Doble Tela",
      subtitle: "Cuello redondo reforzado",
      categoryIds: ["remeras", "s"],
      price: 27000,
      stock: "Quedan 12",
      specs: [
        { label: "Tela", value: "Doble jersey" },
        { label: "Calce", value: "Boxy" },
        { label: "Talles", value: "S – XL" },
      ],
      badges: ["Básico"],
      artSeed: "remera-doble-tela",
    },
    {
      id: "gorro-lana-cruda",
      name: "Gorro Lana Cruda",
      subtitle: "Tejido a mano · pieza única",
      categoryIds: ["accesorios", "m"],
      price: 15000,
      stock: "Quedan 3",
      specs: [
        { label: "Material", value: "Lana cruda" },
        { label: "Origen", value: "Tejido a mano" },
      ],
      badges: ["Pieza única"],
      artSeed: "gorro-lana-cruda",
    },
    {
      id: "pantalon-cargo-tanda04",
      name: "Cargo Tanda 04",
      subtitle: "Sarga reforzada · bolsillos utilitarios",
      categoryIds: ["pantalones", "l"],
      price: 58000,
      stock: "Quedan 6",
      specs: [
        { label: "Tela", value: "Sarga reforzada" },
        { label: "Calce", value: "Relajado" },
        { label: "Talles", value: "S – XL" },
      ],
      badges: ["Tanda 04", "Edición limitada"],
      artSeed: "pantalon-cargo-tanda04",
    },
  ],
};
